server:
  port: 8083

reception:
  services:
    main:
      uri: http://localhost:8080
      username: ${REST_USER}
      password: ${REST_PASSWORD}
    online-record:
      uri: http://localhost:8082
      username: ${REST_USER}
      password: ${REST_PASSWORD}