CREATE SCHEMA IF NOT EXISTS online_schema;

CREATE TABLE IF NOT EXISTS online_schema.t_record
(
    id bigint generated by default as identity primary key,
    phone_client varchar not null check(length(trim(name_client)) > 0),
    name_client varchar not null check(length(trim(name_client)) > 0),
    note_client varchar,
    status_record varchar
);

create index idx_client_phone on online_schema.t_record using hash(phone_client);