CREATE SCHEMA IF NOT EXISTS main_schema;

CREATE TABLE IF NOT EXISTS main_schema.t_client
(
    id bigint generated by default as identity primary key,
    name_client varchar not null check(length(trim(name_client)) > 0),
    phone_client varchar,
    mail_client varchar
);
create index idx_client_name on main_schema.t_client using hash(name_client);

CREATE TABLE IF NOT EXISTS main_schema.t_master
(
    id bigint generated by default as identity  primary key,
    name_master varchar not null check(length(trim(name_master)) > 0),
    phone_master varchar
);
create index idx_master_name on main_schema.t_master using hash(name_master);

CREATE TABLE IF NOT EXISTS main_schema.t_room
(
    id bigint generated by default as identity  primary key,
    number_room varchar not null check(length(trim(note_room)) > 0),
    note_room varchar
);
create index idx_room_number on main_schema.t_room using hash(number_room);

CREATE TABLE IF NOT EXISTS main_schema.t_reception
(
    id bigint generated by default as identity  primary key,
    date_of_visit date,
    finish_time time(6) without time zone,
    start_time time(6) without time zone,
    id_master int not null references main_schema.t_master(id),
    id_client int not null references main_schema.t_client(id),
    id_room int not null references main_schema.t_room(id),
    details varchar
);
create index idx_reception_date on main_schema.t_reception using btree(date_of_visit);
create index idx_reception_master on main_schema.t_reception using btree(id_master);
create index idx_reception_client on main_schema.t_reception using btree(id_client);
create index idx_reception_room on main_schema.t_reception using btree(id_room);

CREATE TABLE IF NOT EXISTS main_schema.t_notification
(
    id bigint generated by default as identity  primary key,
    notification_code varchar not null check(length(trim(notification_code)) > 0),
    notification_name varchar
);

CREATE TABLE IF NOT EXISTS main_schema.t_client_notify
(
    id bigint generated by default as identity  primary key,
    id_client int not null references main_schema.t_client(id),
    id_notification int not null references main_schema.t_notification(id)
);

INSERT INTO main_schema.t_notification(id, notification_code, notification_name)
	VALUES (1, 'PHONE', 'Информирование по телефону');

INSERT INTO main_schema.t_notification(id, notification_code, notification_name)
	VALUES (2, 'MAIL', 'Информирование по электронной почте');