server:
  port: 8081

reception:
  name: массажный салон
  subject: Оповещение о записи

spring:
  kafka:
    bootstrap-servers: localhost:9092
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    debug: true
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
mail:
  debug: true

kafka:
  topics:
    mail: mailNotify_1
    phone: phoneNotify_1